import type { NextPage } from 'next'
import Head from 'next/head'
import { useRouter } from 'next/router'
import { useEffect } from 'react'
import { useUser } from '../src/hooks/useUser'

const Home: NextPage = () => {
  const { user, signIn } = useUser()
  const router = useRouter()

  useEffect(() => {
    if (!user) router.push('/signin')
  }, [])

  return (
    <div className=''>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <section>Test</section>
    </div>
  )
}

export default Home
