import type { InferGetStaticPropsType, NextPage } from 'next'
import Head from 'next/head'
import { useRouter } from 'next/router'
import { useEffect } from 'react'
import { useUser } from '../src/hooks/useUser'

import { GetStaticProps } from 'next'
import Product from '../src/components/Product'
import ApiHelper from '../src/ApiHelper'
import IProduct from '../src/types/IProduct'
import AddProductHeader from '../src/components/AddProductHeader'

export const getStaticProps: GetStaticProps = async (context) => {
  const products: IProduct[] = await ApiHelper.getItems<IProduct>(
    'https://purchasetips.azurewebsites.net/api/allproducts'
  )
  return {
    revalidate: 1,

    props: {
      products: products,
    },
  }
}

const Home: NextPage = ({
  products,
}: InferGetStaticPropsType<typeof getStaticProps>) => {
  const { user } = useUser()
  const router = useRouter()

  useEffect(() => {
    if (!user) router.push('/signin')
  }, [])

  return (
    <div className=''>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <AddProductHeader />

      <section className='mt-6 grid grid-cols-1 gap-y-10 gap-x-6 sm:grid-cols-2 lg:grid-cols-4 xl:gap-x-8 '>
        {products.map((x: IProduct) => (
          <Product key={x.Id} product={x} />
        ))}
      </section>
    </div>
  )
}

export default Home
