import type { NextPage } from 'next'
import Head from 'next/head'
import Account from '../src/components/Account'

const Profile: NextPage = () => {
  return (
    <div className=''>
      <Head>
        <title>profile</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <section>Settings will come here... </section>
    </div>
  )
}

export default Profile
